#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------

resolver: nightly-2024-12-27
# resolver: lts-23.1

#nix:
#  enable: true
#
