#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------

resolver: lts-23.1

#nix:
#  enable: true
#
